pipeline {
    agent any

    stages {
        stage('Clone Code') {
            steps {
                git 'https://github.com/KRISHkg31/CI-CD-PipeLine' // Add your GitHub repo URL
            }
        }
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh 'npm test'
            }
        }
        stage('Docker Build & Push') {
            steps {
                script {
                    docker.build('my-node-app').push('my-node-app:latest')
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f k8s/deployment.yaml'
            }
        }
    }
}
